import type { Metadata } from "next";
import localFont from "next/font/local";
import { i18n } from "@/i18n-config";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { ModeToggle } from "@/components/ui/theme-toggle";
import { LocaleSwitcher } from "@/components/ui";
import StoreProvider from "@/store/StoreProvider";

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html
      lang={lang}
      suppressHydrationWarning
      className="scroll-smooth focus:scroll-auto"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider lastUpdate={new Date().getTime()}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <nav>
              <ul className="flex justify-between p-4">
                <div className="flex gap-4">
                  <Link href={`/${lang}`}>Home</Link>
                  <Link href={`/${lang}/about`}>About</Link>
                </div>
                <ModeToggle />
                <LocaleSwitcher lang={lang} />
              </ul>
            </nav>
            {children}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
